#ifndef UTILS_H
#define UTILS_H
#include "item.h"
#include "inventory.h"

#define GAME_LANG_ENGLISH 0
#define GAME_LANG_FRENCH 1

typedef struct {
    int language; // 0: English, 1: French
    float max_weight;
} GameSettings;

enum {
    MSG_MENU_TITLE, MSG_ADVENTURE, MSG_SHOP, MSG_BROWSE,
    MSG_SETTINGS, MSG_ACTUAL_SETTINGS, MSG_CREDITS, MSG_QUIT,
    MSG_INVALID_CHOICE, MSG_CHANGE_LANGUAGE, MSG_CHANGE_MAX_WEIGHT,
    MSG_ACTUAL_MAX_WEIGHT, MSG_ADD_ITEM, MSG_BACK, MSG_ENGLISH,
    MSG_FRENCH, MSG_LANGUAGE_UPDATED, MSG_MAX_WEIGHT_UPDATED,
    MSG_INVALID_WEIGHT, MSG_ITEM_CREATED, MSG_FAILED_TO_CREATE_ITEM,
    MSG_ENTER_ITEM_NAME, MSG_SELECT_ITEM_TYPE, MSG_SELECT_ITEM_RARITY,
    MSG_SELECT_ITEM_STATE, MSG_ENTER_ITEM_DESCRIPTION,
    MSG_ENTER_ITEM_WEIGHT, MSG_ENTER_ITEM_VALUE, MSG_ENTER_PASSIVE_EFFECT,
    MSG_ENTER_MIN_DAMAGE, MSG_ENTER_MAX_DAMAGE, MSG_ENTER_DAMAGE_TYPE,
    MSG_ENTER_DURABILITY, MSG_ENTER_RANGE, MSG_ENTER_ATTACK_SPEED,
    MSG_ENTER_DEFENSE, MSG_ENTER_RESISTANCES, MSG_SELECT_SLOT,
    MSG_ENTER_MOVEMENT_PENALTY, MSG_ENTER_EFFECT, MSG_ENTER_DURATION,
    MSG_ENTER_USE_TIME, MSG_ENTER_CHARGES, MSG_ENTER_QUEST_ID,
    MSG_ENTER_STORY, MSG_ENTER_HARVEST_LOCATION, MSG_SELECT_LANGUAGE,
    MSG_INVENTORY_EMPTY, MSG_WEAPON, MSG_ARMOR, MSG_CONSUMABLE,
    MSG_QUEST_ITEM, MSG_MATERIAL, MSG_WORTHLESS, MSG_COMMON, MSG_RARE,
    MSG_EPIC, MSG_LEGENDARY, MSG_MYTHIC, MSG_DIVINE, MSG_NEW, MSG_WORN,
    MSG_BROKEN, MSG_CURSED, MSG_SELECT_OPTION, MSG_YOUR_CHOICE,
    MSG_ITEM_NAME, MSG_ITEM_TYPE, MSG_ITEM_RARITY, MSG_ITEM_STATE,
    MSG_ITEM_DESCRIPTION, MSG_ITEM_WEIGHT, MSG_ITEM_VALUE,
    MSG_ITEM_PASSIVE_EFFECT, MSG_ITEM_MIN_DAMAGE, MSG_ITEM_MAX_DAMAGE,
    MSG_ITEM_DAMAGE_TYPE, MSG_ITEM_DURABILITY, MSG_ITEM_RANGE,
    MSG_ITEM_ATTACK_SPEED, MSG_ITEM_DEFENSE, MSG_ITEM_RESISTANCES,
    MSG_ITEM_SLOT, MSG_ITEM_MOVEMENT_PENALTY, MSG_ITEM_EFFECT,
    MSG_ITEM_DURATION, MSG_ITEM_USE_TIME, MSG_ITEM_CHARGES,
    MSG_ITEM_QUEST_ID, MSG_ITEM_STORY, MSG_ITEM_HARVEST_LOCATION,
    MSG_HEAD, MSG_CHEST, MSG_LEGS, MSG_HANDS, MSG_OFFHAND,
    MSG_INVENTORY_FULL, MSG_ACTUAL_BAG_WEIGHT, MSG_WALLET,
    MSG_ENTER_NAME_FR, MSG_ENTER_DESCRIPTION_FR, MSG_ENTER_PASSIVE_EFFECT_FR,
    MSG_ENTER_DAMAGE_TYPE_FR, MSG_ENTER_RESISTANCES_FR, MSG_ENTER_EFFECT_FR,
    MSG_ENTER_STORY_FR, MSG_ENTER_HARVEST_LOCATION_FR, MSG_NOT_ENOUGH_GOLD,
    MSG_SELL_ITEMS, MSG_ITEM_SOLD
};

int get_random_int(int min, int max);
void clear_input_buffer(void);
void display_banner(void);
const char* get_message(int message_id, int language);
void display_credits(int language);
void configure_settings(GameSettings* settings, Inventory* inv, ItemDatabase* db);
Item* create_item_from_menu(int language, ItemDatabase* db);

#endif